---
- name: Install qemu and related tools
  dnf:
    name:
      - qemu
      - qemu-kvm
      - qemu-img
      - libvirt
      - libvirt-python
      - libvirt-client
      - virt-install
      - vagrant-libvirt
    state: latest

- name: Install Vagrant plugins
  become: True
  shell: "vagrant plugin install {{ item.name }}"
  with_items:
    -vagrant-libvirt
