---

- name: "enable repos"
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - azure-cli.repo
    - openresty.repo

# Vagrant

- name: Ensure temp download directory exist
  file: state=directory path={{vagrant_tmp_dir}}
  tags: ["packages","vagrant"]

- name: Download vagrant
  get_url: url={{ vagrant_url_rpm }} dest={{vagrant_tmp_rpm}}

- name: Install vagrant
  dnf: name={{vagrant_tmp_rpm}}

# Vault

- name: Download Vault
  get_url:
    url: "{{ vault_zip_url }}"
    dest: "{{ vault_dest }}"

- name: Unarchive Vault
  unarchive:
    src: "{{ vault_dest }}"
    dest: "/usr/local/bin"
    creates: "/usr/local/bin/vault"

- name: copy bash profile for vault profile
  copy:
    src: vault_profile
    owner: "{{ansible_user_id}}"    
    group: "{{ansible_user_id}}"
    mode: 0755
    force: no
    dest: "~{{ansible_user_id}}/.bash_profile.d"
  become: false

- name: copy bash profile for git
  copy:
    src: git_profile
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    mode: 0755
    force: no
    dest: "~{{ansible_user_id}}/.bash_profile.d"
  become: false

- name: Download Packer
  get_url:
    url: "{{ packer_zip_url }}"
    dest: "{{ packer_dest }}"

- name: Unarchive Packer
  unarchive:
    src: "{{ packer_dest }}"
    dest: "/usr/local/bin"
    creates: "/usr/local/bin/packer"

# front end testing.
- name: Install QT and webkit
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - qt5
    - chromedriver

- name: Postgres
  dnf:
    name: ["postgresql"]
    state: latest

# Python
- name: PyPy
  dnf:
    name: ["pypy"]
    state: latest
