---

# Local Stack Config
- lineinfile:
    path: /etc/hosts
    regexp: 'watcher0'
    line: '192.168.99.90 watcher0 local.watcher api.local.watcher repo.local.watcher pkg.local.watcher nx.local.watcher rabbitmq mq0.local.watcher mq1.local.watcher'
    owner: root
    group: root
    mode: 0644

- name: copy bash profile for docker profile
  copy:
    src: docker_profile
    dest: "~{{ansible_user_id}}/.bash_profile.d/docker_profile"
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    mode: 0755
  become: false

- name: copy bash profile for docker profile
  copy:
    src: docker_profile
    dest: "~{{ansible_user_id}}/.bash_profile.d/agent_api"
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    mode: 0755
  become: false

- name: Ensure temp download directory exist
  file:
    path: "{{monitoring_root}}"
    owner: "{{ansible_user_id}}"
    state: directory

# Note: I couldn't get this to work without prompting everytime.  Might need to run command with sudo to the correct user.
- name: Checkout src
  git:
    repo: 'https://github.com/CenturyLinkCloud/{{item}}.git'
    dest: "{{monitoring_root}}/{{item}}"
    key_file: /root/.ssh/github
    accept_hostkey: yes
    clone: yes
    update: no
  become: yes
  become_user: "{{ansible_user_id}}"
  with_items:
    - mon-infrastructure
    - mon-docker-images
    - mon-agent
    - mon-agent-repo
    - mon-sensu
    - mon-ui
    - mon-testing
    - mon-agent-api
    - mon-policy-config-api
    - mon-metrics-api
    - mon-events-api
    - mon-api-lib
    - mon-sensu-extensions-wizardvan
    - mon-sensu-extensions-influxdb
    - mon-sensu-plugins-snmp

- name: Change project dir owner
  file:
    path: "{{monitoring_root}}/{{item}}"
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
  with_items:
    - mon-infrastructure
    - mon-docker-images
    - mon-agent
    - mon-agent-repo
    - mon-sensu
    - mon-ui
    - mon-testing
    - mon-agent-api
    - mon-policy-config-api
    - mon-metrics-api
    - mon-events-api
    - mon-api-lib
    - mon-sensu-extensions-wizardvan
    - mon-sensu-extensions-influxdb
    - mon-sensu-plugins-snmp
