---

- name: Download repo
  get_url:
    url: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
    dest: /etc/yum.repos.d/virtualbox.repo


- name: Install deps
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - binutils
    - qt
    - gcc
    - make
    - patch
    - libgomp
    - glibc-headers
    - glibc-devel
    - kernel-headers
    - kernel-devel
    - dkms

- name: Install VirtualBox
  dnf:
    name: "VirtualBox-5.1"
    state: present

- name: Rebuild kernel moduels
  command: /usr/lib/virtualbox/vboxdrv.sh setup
