- name: Add terraform repo
  get_url:
    url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install terraform
  dnf:
    name: terraform
    state: latest
