---

- name: install vim
  dnf:
    name: vim
    state: latest

- name: install gnome-tweak-tool
  dnf:
    name: gnome-tweak-tool
    state: latest    

- name: install keepass
  dnf:
    name: keepass
    state: latest

- name: install jq
  dnf:
    name: jq
    state: latest

- name: install jq
  dnf:
    name: bonnie++
    state: latest


- name: Install openVPN
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - NetworkManager-openvpn
    - NetworkManager-openvpn-gnome
    - openvpn

- name: Install gpast
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - gpaste
    - gpaste-ui
    - gnome-shell-extension-gpaste

- name: copy bash profile
  copy:
    src: .bash_profile
    dest: "~{{ansible_user_id}}/.bash_profile"
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    mode: 0755
  become: false

- name: ensure profile.d dir exists
  file:
    path: "~{{ansible_user_id}}/.bash_profile.d"
    state: directory
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"

