---

- name: "enable repos"
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - slack.repo
    
- name: install vim
  dnf:
    name: vim
    state: latest

- name: install gnome-tweak-tool
  dnf:
    name: gnome-tweak-tool
    state: latest

- name: install keepass
  dnf:
    name: keepass
    state: latest

- name: install jq
  dnf:
    name: jq
    state: latest

- name: install strongswan
  dnf:
    name: strongswan
    state: latest

- name: install remmina
  dnf:
    name: remmina
    state: latest

- name: install clamav
  dnf:
    name: clamav
    state: latest

- name: install net-snmp-utils
  dnf:
    name: net-snmp-utils
    state: latest

- name: install inkscape
  dnf:
    name: inkscape
    state: latest

- name: install dolphin
  dnf:
    name: dolphin
    state: latest

- name: install jq
  dnf:
    name: bonnie++
    state: latest


- name: Install openVPN
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - NetworkManager-openvpn
    - NetworkManager-openvpn-gnome
    - openvpn

- name: Install gpast
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - gpaste
    - gpaste-ui
    - gnome-shell-extension-gpaste

- name: copy bash profile
  copy:
    src: .bash_profile
    dest: "~{{ansible_user_id}}/.bash_profile"
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    mode: 0755
  become: false

- name: Ensure bash_profile is sourced from .bashrc
  lineinfile:
    path: "~{{ansible_user_id}}/.bashrc"
    regexp: 'bash_profile'
    line: '. ~/.bash_profile'
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"

- name: ensure profile.d dir exists
  file:
    path: "~{{ansible_user_id}}/.bash_profile.d"
    state: directory
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"

