---

# vagrant
vagrant_version: "2.2.2"
vagrant_tmp_dir: "/tmp/ansible_downloads/"
vagrant_tmp_rpm: "{{vagrant_tmp_dir}}/vagrant_{{vagrant_version}}.rpm"

vagrant_url_rpm: "https://releases.hashicorp.com/vagrant/{{vagrant_version}}/vagrant_{{vagrant_version}}_{{ansible_architecture}}.rpm"

# Vault
vault_version: 0.8.3
vault_zip_url: "https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip"
vault_dest: "/tmp/vault_{{vault_version}}_linux_amd64.zip"

# packer
packer_version: 1.3.3
packer_zip_url: "https://releases.hashicorp.com/packer/{{packer_version}}/packer_{{packer_version}}_linux_amd64.zip"
packer_dest: "/tmp/vault_{{packer_version}}_linux_amd64.zip"
