---
- name: install the Development tools package group
  dnf:
    name: '@C Development Tools and Libraries'
    state: present

# Easy win for installing latest ruby in the system
# It will result in multiple versions of the same ruby from chruby
# but this is more easily excessible
- name: Install ruby, rubygems, and development tools.
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - ruby
    - ruby-devel
    - rubygem-json

- name: Install Bundler.
  gem:
    name: bundler
    state: present
    user_install: no

- name: install common ruby deps
  dnf:
    name: "{{item}}"
    state: latest
  with_items:
    - postgresql-devel
    - patch
    - libxml-devel
    - zlib-devel
    - readline-devel
    - libyaml-devel
    - openssl-devel
    - autoconf automake
    - libtool
    - sqlite-devel

- name: Download chruby repo config
  get_url:
    url: "https://copr.fedorainfracloud.org/coprs/postmodern/chruby/repo/fedora-28/postmodern-chruby-fedora-28.repo"
    dest: "/etc/yum.repos.d/postmodern-chruby-fedora-28.repo"

- name: Install chruby
  dnf:
    name: "{{item}}"
    state: latest
  with_items:
    - chruby
    - ruby-install

- name: copy bash profile
  copy:
    src: ruby_profile
    dest: "~{{ansible_user_id}}/.bash_profile.d/ruby_profile"
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    mode: 0755
  become: false

- name: Install additional rubies
  become: true
  with_items:
    - "2.3"
  shell:
    creates: "/opt/rubies/ruby-{{ item }}/bin/ruby"
    command: "ruby-install ruby {{ item }}"

- name: Install bundler for rubies
  become: true
  with_items:
   - "2.3"
  shell:
    creates: "/opt/rubies/ruby-{{ item }}/bin/bundle"
    command: "source /usr/local/share/chruby/chruby.sh && chruby {{ item }} && gem install bundler"



