---
- name: install the Development tools package group
  dnf:
    name: '@C Development Tools and Libraries'
    state: present

- name: Install ruby, rubygems, and development tools.
  dnf: 
    name: "{{ item }}" 
    state: present
  with_items:
    - ruby
    - ruby-devel

- name: Install Bundler.
  gem: 
    name: bundler 
    state: present 
    user_install: no

-name: install common ruby deps
  dnf:
    name: "{{item}}"
    state: latest
  with_items:
    - postgresql-devel
    - patch
    - libxml-devel
    - zlib-devel
    - readline-devel
    - libyaml-devel
    - openssl-devel
    - autoconf automake
    - libtool
    - sqlite-devel

