---
- name: install the Development tools package group
  dnf:
    name: '@C Development Tools and Libraries'
    state: present

# Easy win for installing latest ruby in the system
# It will result in multiple versions of the same ruby from chruby
# but this is more easily excessible
- name: Install ruby, rubygems, and development tools.
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - ruby
    - ruby-devel
    - rubygem-json

- name: Install Bundler.
  gem:
    name: bundler
    state: present
    user_install: no

- name: install common ruby deps
  dnf:
    name: "{{item}}"
    state: latest
  with_items:
    - postgresql-devel
    - patch
    - libxml-devel
    - zlib-devel
    - readline-devel
    - libyaml-devel
    - openssl-devel
    - autoconf 
    - automake
    - libtool
    - sqlite-devel

- name: copy bash profile
  copy:
    src: ruby_profile
    dest: "~{{ansible_user_id}}/.bash_profile.d/ruby_profile"
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    mode: 0755
  become: false
